### ISSUE TITLE
Invalid handler type "console" given for handler "console" during setup

### ISSUE THREAD

**Issue by gevatter** [phpugl/Dime#77]
When running

    app/console dime:publish-assets --env=prod

during setup i get following error:

    [InvalidArgumentException]
    Invalid handler type "console" given for handler "console"

I could work around that by commenting out the lines

    console:
        type:  console

in

    app/config/config_prod.yml

    # php54 -v
    PHP 5.4.32 (cli) (built: Sep 11 2014 15:34:18)
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by nogo** [comment]
fixed with 3ba9c8e6a83a6812c8ccdbbd6a19d37c34a9ddd4
