### ISSUE TITLE
The template should be a string or extend TemplateReference

### ISSUE THREAD

**Issue by SOYOS** [phpugl/Dime#80]
500 Internal Server Error after Login - any solution?:

Stack Trace
in vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/View/View.php at line 218   -
    public function setTemplate($template)
    {
        if (!(is_string($template) || $template instanceof TemplateReference)) {
            throw new \InvalidArgumentException('The template should be a string or extend TemplateReference');
        }
        $this->template = $template;

**Comment by nogo** [comment]
@SOYOS is this problem after you installed Dime?

**Comment by SOYOS** [comment]
Fixed with installing the master! Thx
